#install.packages ("sparklyr") 
#install.packages ("dplyr") 
#install.packages ("titanic") 
#install.packages ("pryr")
library (sparklyr) 
library (dplyr) 
library (titanic) 
library (pryr)
spark_install (version = "3.0.1")